name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
    
  docker-build-oobabooga:
    uses: localagi/ai-dedicated-workflows/.github/workflows/operation-docker-build-publish.yml@v3
    with:
      pre-free-disk-space: true
      registry-repo-name: oobabooga
      context-repository: https://github.com/oobabooga/text-generation-webui.git
      context-repository-ref: ${{ github.ref_name }}
      dockerfile: https://raw.githubusercontent.com/oobabooga/text-generation-webui/${{ github.ref }}/docker/Dockerfile
      tags: |
        type=schedule
        type=ref,event=branch
        type=raw,value=${{ github.ref_name }}
      flavor: |
        suffix=-cc-${{ matrix.compute_version_id || matrix.compute_version }}
      build-args: |
        TORCH_CUDA_ARCH_LIST=${{ matrix.compute_version }}
      #  WEBUI_VERSION=309b72e54970e640ef8bfb5071f1be5c31f5e798 
      #${WEBUI_VERSION:-'HEAD'}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        # see https://pytorch.org/docs/stable/cpp_extension.html
        compute_version: ["6.1", "8.6+PTX"]

        include:
          - compute_version_id: 8.6PTX #fix invalid docker name
            compute_version: "8.6+PTX"
